### ISSUE TITLE
I'm trying to do this in Swift

### ISSUE THREAD

**Issue by leonardbonfils** [versluis/3D-Touch#1]
I've been trying to get 3D Preview Action Items to work for like 2 weeks and they just won't work...

Can you help ?

Here is a screenshot of part of my storyboard. I want to launch directly into "Saved Articles".

http://imgur.com/4uwzxgK

This is my code, which for some reason isn't working even though I'm literally doing the EXACT same thing as you:

http://imgur.com/HZphWAJ

**Comment by versluis** [comment]
If I understand correctly, you'd like to launch from a shortcut item and show a deep linked view controller. So what exactly isn't working, triggering the shortcut or launching the view controller?

Looking at your code and storyboard, if Saved Articles is the controller you want displayed, then it's enough to instantiate the navigation controller in front if it - there's no need to push Saved Articles onto the stack. This is only necessary if you were to show the second or third level after that.

**Comment by leonardbonfils** [comment]
I don't actually know which one isn't working. All I see is that when I tap the 3D Touch shortcut item, it just brings me to the normal launch view controller. It's extremely frustrating...

I also tried just instantiating the specific navigation controller... it still wouldn't work. Any ideas ?

**Comment by versluis** [comment]
Take it one step at a time: add a log message or breakpoint where the shortcut is triggered and see if that works. Once that's sorted, make sure the navigation controller has the Storyboard ID you're instantiating. 

I don't speak Swift well enough to help you with that though, but I'd probably try to create a separate dummy project and practice instantiating that view controllers in there, then transfer your findings to your working project.

Good luck!

**Comment by leonardbonfils** [comment]
Just added a few print statements. The shortcuts in my handleShortcut method are being properly triggered based on which shortcut item I tap on. So it's just the part where I need to show the correct view controller that I can't get to work. I feel like it the problem might be due to me using a SWRevealViewController in my project. Maybe that reveal view controller forces the starting view to always be the first view in the reveal menu...

**Comment by versluis** [comment]
I doubt it, because you're changing root view controllers. That overrides everything else.

**Comment by versluis** [comment]
Right, I've worked out how to switch view controllers in Swift. Here's a demo project: https://github.com/versluis/Swift-Switch

Swift isn't so hard after all... just weird when you're coming from Objective-C :+1:

**Comment by leonardbonfils** [comment]
Objective-C looks weird to me lol.

I just changed my "let storyboard" line to be like yours (with the init) and removed the "makeKeyAndVisible" line since that wasn't in your program. I get a "unexpectedly found nil while unwrapping an optional value" error... The only optional I am unwrapping is window. How the heck is my window nil ? I clearly have that typical "var window: UIWindow?" statement in my app delegate...

**Comment by versluis** [comment]
That sucks indeed. And that's in your AppDelegate? How can the window be nil?

I've rewritten the whole project in Swift - it was a good exercise. Swift kept throwing curveballs at me! Maybe it helps you hunt down those pesky bugs in your project: 
- https://github.com/versluis/3D-Touch-Swift

**Comment by leonardbonfils** [comment]
I have no idea how the window can be nil. When I fix this bug, I'll tell you.

On Dec 6, 2015, at 14:32, Jay Versluis <notifications@github.com<mailto:notifications@github.com>> wrote:

That sucks indeed. And that's in your AppDelegate? How can the window be nil?

I've rewritten the whole project in Swift - it was a good exercise. Swift kept throwing curveballs at me! Maybe it helps you hunt down those pesky bugs: https://github.com/versluis/3D-Touch-Swift

##
