### ISSUE TITLE
Force touch the app icon when app closed from task manager open home screen

### ISSUE THREAD

**Issue by DinaHussieny** [versluis/3D-Touch#2]
while using quick actions of 3D Touch it works good but while app is terminated first time force touch the app icon it open home screen but the other times it open the right screen

**Comment by versluis** [comment]
When the app is closed (cold launch), Deep Link 1 and Deep Link 2 open the respective navigation controllers. The Static and Dynamic shortcut items both open the Main View. This is expected behaviour.
